name: testing
on:
  pull_request:
  merge_group:
  schedule:
    - cron: '45 23 * * 4' # 11:45PM UTC Daily (approx 1.75 hours after coreos images publish)
  workflow_dispatch:

jobs:
  build-testing:
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      coreos_version: testing
