name: stable
on:
  pull_request:
  merge_group:
  schedule:
    - cron: '00 0 * * 0' # 11:45PM UTC Sunday (approx 1.5 hours after coreos images publish)
  workflow_dispatch:

jobs:
  build-stable:
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      coreos_version: stable
